
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-server
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    volumes:
      - redis-data:/data

  resume-service:
    build: ../resume-processing-service
    ports:
      - "4000:4000"
    depends_on:       # ensures Redis starts first.
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  jobmatching-service:
    build: ../jobmatching-and-ranking-service
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  communication-service:
    build: ../communication-and-interview-scheduling-service
    ports:
      - "6000:6000"
      - "6002:6002"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  authentication-service:
    build: ../authentication-service
    ports:
      - "7000:7000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  
  


volumes:
  redis-data:


  #docker-compose up -d 
  #docker-compose down
  #use redis stacjk for redis GUI  //go to localhost 8001
  # docker-compose up -d --build